"""Private runtime references for the progressive PyTorch broadcasting workbook."""

from __future__ import annotations

import torch

CASES = {'ex001': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'basic'},
 'ex002': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'basic'},
 'ex003': {'expression': 'a * b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'basic'},
 'ex004': {'expression': 'a - b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'basic'},
 'ex005': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'basic'},
 'ex006': {'expression': 'a * b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'basic'},
 'ex007': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex008': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex009': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex010': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex011': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex012': {'expression': 'a - b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex013': {'expression': 'a * b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex014': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex015': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex016': {'expression': 'a * b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex017': {'expression': 'a / b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex018': {'expression': 'a * b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex019': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex020': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex021': {'expression': 'rows_col * grid',
           'intermediates': {'rows_col': 'rows[:, None]'},
           'audit': ['rows_col', 'grid'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex022': {'expression': 'cols_row + grid',
           'intermediates': {'cols_row': 'cols[None, :]'},
           'audit': ['cols_row', 'grid'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex023': {'expression': 'features_view + cube',
           'intermediates': {'features_view': 'features[None, None, :]'},
           'audit': ['features_view', 'cube'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex024': {'expression': 'batch_view * cube',
           'intermediates': {'batch_view': 'batch_values[:, None, None]'},
           'audit': ['batch_view', 'cube'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex025': {'expression': 'channel_view + images',
           'intermediates': {'channel_view': 'channels[None, :, None, None]'},
           'audit': ['channel_view', 'images'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex026': {'expression': 'height_view * images',
           'intermediates': {'height_view': 'heights[None, None, :, None]'},
           'audit': ['height_view', 'images'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex027': {'expression': 'width_view * images',
           'intermediates': {'width_view': 'widths[None, None, None, :]'},
           'audit': ['width_view', 'images'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex028': {'expression': 'prepared + sequence',
           'intermediates': {'prepared': 'per_batch_feature[:, None, :]'},
           'audit': ['prepared', 'sequence'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex029': {'expression': 'mask_view * features',
           'intermediates': {'mask_view': 'mask[:, :, None]'},
           'audit': ['mask_view', 'features'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex030': {'expression': 'gain_view * images',
           'intermediates': {'gain_view': 'gain[None, :, None, :]'},
           'audit': ['gain_view', 'images'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex031': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex032': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex033': {'expression': 'a * b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex034': {'expression': 'images + bias',
           'intermediates': {},
           'audit': ['images', 'bias'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex035': {'expression': 'images * scale',
           'intermediates': {},
           'audit': ['images', 'scale'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex036': {'expression': 'images + spatial',
           'intermediates': {},
           'audit': ['images', 'spatial'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex037': {'expression': 'images * gain',
           'intermediates': {},
           'audit': ['images', 'gain'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex038': {'expression': 'tokens + positions',
           'intermediates': {},
           'audit': ['tokens', 'positions'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex039': {'expression': 'scores + head_bias',
           'intermediates': {},
           'audit': ['scores', 'head_bias'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex040': {'expression': 'query_values + key_values',
           'intermediates': {},
           'audit': ['query_values', 'key_values'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex041': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex042': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex043': {'expression': 'torch.where(mask, values, torch.zeros_like(values))',
           'intermediates': {},
           'audit': ['mask', 'values'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex044': {'expression': 'images - mean',
           'intermediates': {},
           'audit': ['images', 'mean'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex045': {'expression': 'x * scale + bias',
           'intermediates': {},
           'audit': ['x', 'scale', 'bias'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex046': {'expression': 'a * b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex047': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex048': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex049': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex050': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex051': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex052': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex053': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex054': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex055': {'expression': 'torch.where(mask, x, y)',
           'intermediates': {},
           'audit': ['mask', 'x', 'y'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': False,
           'mode': 'invalid'},
 'ex056': {'expression': 'source.expand_as(target)',
           'intermediates': {},
           'audit': ['source', 'target'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex057': {'expression': 'source.expand_as(target)',
           'intermediates': {},
           'audit': ['source', 'target'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex058': {'expression': 'source.expand_as(target)',
           'intermediates': {},
           'audit': ['source', 'target'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex059': {'expression': 'source.expand_as(target)',
           'intermediates': {},
           'audit': ['source', 'target'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex060': {'expression': 'torch.broadcast_to(source, target.shape)',
           'intermediates': {},
           'audit': ['source', 'target'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex061': {'expression': 'source.expand_as(target)',
           'intermediates': {},
           'audit': ['source', 'target'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex062': {'expression': 'source.repeat(2, 1)',
           'intermediates': {},
           'audit': ['source'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex063': {'expression': 'source.repeat(1, 3)',
           'intermediates': {},
           'audit': ['source'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex064': {'expression': 'source.expand(2, 3)',
           'intermediates': {},
           'audit': ['source'],
           'value_exprs': {'shares_storage': 'out.untyped_storage().data_ptr() == '
                                             'source.untyped_storage().data_ptr()'},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex065': {'expression': 'source.expand(2, 3).clone()',
           'intermediates': {},
           'audit': ['source'],
           'value_exprs': {'shares_storage': 'out.untyped_storage().data_ptr() == '
                                             'source.untyped_storage().data_ptr()'},
           'backward': [],
           'expected_compatible': True,
           'mode': 'result'},
 'ex066': {'expression': 'torch.where(mask, x, fallback)',
           'intermediates': {},
           'audit': ['mask', 'x', 'fallback'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex067': {'expression': 'torch.where(mask, x, y)',
           'intermediates': {},
           'audit': ['mask', 'x', 'y'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex068': {'expression': 'torch.where(mask, x, y)',
           'intermediates': {},
           'audit': ['mask', 'x', 'y'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex069': {'expression': 'torch.where(mask, x, y)',
           'intermediates': {},
           'audit': ['mask', 'x', 'y'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex070': {'expression': 'torch.maximum(x, threshold)',
           'intermediates': {},
           'audit': ['x', 'threshold'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex071': {'expression': 'torch.minimum(x, limit)',
           'intermediates': {},
           'audit': ['x', 'limit'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex072': {'expression': 'mask * x',
           'intermediates': {},
           'audit': ['mask', 'x'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex073': {'expression': 'a + b + c',
           'intermediates': {},
           'audit': ['a', 'b', 'c'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex074': {'expression': 'alpha * x + (1 - alpha) * y',
           'intermediates': {},
           'audit': ['alpha', 'x', 'y'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex075': {'expression': 'torch.lerp(start, end, weight)',
           'intermediates': {},
           'audit': ['start', 'end', 'weight'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex076': {'expression': 'activations + bias',
           'intermediates': {},
           'audit': ['activations', 'bias'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex077': {'expression': 'activations + offset',
           'intermediates': {},
           'audit': ['activations', 'offset'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex078': {'expression': 'normalized * gain',
           'intermediates': {},
           'audit': ['normalized', 'gain'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex079': {'expression': '(x - mean) / std',
           'intermediates': {},
           'audit': ['x', 'mean', 'std'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex080': {'expression': 'normalized * gamma + beta',
           'intermediates': {},
           'audit': ['normalized', 'gamma', 'beta'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex081': {'expression': 'token_embeddings + position_embeddings',
           'intermediates': {},
           'audit': ['token_embeddings', 'position_embeddings'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex082': {'expression': 'mask_view * embeddings',
           'intermediates': {'mask_view': 'mask[:, :, None]'},
           'audit': ['mask_view', 'embeddings'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex083': {'expression': 'weights_view * token_losses',
           'intermediates': {'weights_view': 'weights[:, None]'},
           'audit': ['weights_view', 'token_losses'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex084': {'expression': 'losses * class_weights',
           'intermediates': {},
           'audit': ['losses', 'class_weights'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex085': {'expression': 'bias_view + images',
           'intermediates': {'bias_view': 'bias[None, :, None, None]'},
           'audit': ['bias_view', 'images'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex086': {'expression': 'gain_view * images',
           'intermediates': {'gain_view': 'gain[None, :, None, None]'},
           'audit': ['gain_view', 'images'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex087': {'expression': 'scores.masked_fill(~mask, -1e9)',
           'intermediates': {},
           'audit': ['scores', 'mask'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex088': {'expression': 'scale_view * scores',
           'intermediates': {'scale_view': 'head_scale[None, :, None, None]'},
           'audit': ['scale_view', 'scores'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex089': {'expression': 'weight_view * experts',
           'intermediates': {'weight_view': 'weights[:, :, None]'},
           'audit': ['weight_view', 'experts'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex090': {'expression': 'x_rows - y_rows',
           'intermediates': {'x_rows': 'x[:, None, :]', 'y_rows': 'y[None, :, :]'},
           'audit': ['x_rows', 'y_rows'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'aligned'},
 'ex091': {'expression': 'x + bias',
           'intermediates': {},
           'audit': ['x', 'bias'],
           'value_exprs': {},
           'backward': ['x', 'bias'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex092': {'expression': 'x + bias',
           'intermediates': {},
           'audit': ['x', 'bias'],
           'value_exprs': {},
           'backward': ['x', 'bias'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex093': {'expression': 'x + bias',
           'intermediates': {},
           'audit': ['x', 'bias'],
           'value_exprs': {},
           'backward': ['x', 'bias'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex094': {'expression': 'x * scale',
           'intermediates': {},
           'audit': ['x', 'scale'],
           'value_exprs': {},
           'backward': ['x', 'scale'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex095': {'expression': 'x * scale',
           'intermediates': {},
           'audit': ['x', 'scale'],
           'value_exprs': {},
           'backward': ['x', 'scale'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex096': {'expression': 'x + bias',
           'intermediates': {},
           'audit': ['x', 'bias'],
           'value_exprs': {},
           'backward': ['x', 'bias'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex097': {'expression': 'images + bias',
           'intermediates': {},
           'audit': ['images', 'bias'],
           'value_exprs': {},
           'backward': ['images', 'bias'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex098': {'expression': 'a + b',
           'intermediates': {},
           'audit': ['a', 'b'],
           'value_exprs': {},
           'backward': ['a', 'b'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex099': {'expression': '(x + bias) ** 2',
           'intermediates': {},
           'audit': ['x', 'bias'],
           'value_exprs': {},
           'backward': ['x', 'bias'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex100': {'expression': 'x / scale',
           'intermediates': {},
           'audit': ['x', 'scale'],
           'value_exprs': {},
           'backward': ['x', 'scale'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex101': {'expression': 'x - x.mean(dim=0, keepdim=True)',
           'intermediates': {},
           'audit': ['x'],
           'value_exprs': {},
           'backward': ['x'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex102': {'expression': 'normalized * gamma + beta',
           'intermediates': {},
           'audit': ['normalized', 'gamma', 'beta'],
           'value_exprs': {},
           'backward': ['normalized', 'gamma', 'beta'],
           'expected_compatible': True,
           'mode': 'backward'},
 'ex103': {'expression': 'normalized',
           'intermediates': {'mean': 'x.mean(dim=0, keepdim=True)',
                             'centered': 'x - mean',
                             'variance': '(centered ** 2).mean(dim=0, keepdim=True)',
                             'inv_std': '(variance + 1e-5).rsqrt()',
                             'normalized': 'centered * inv_std'},
           'audit': ['x'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'capstone'},
 'ex104': {'expression': 'normalized',
           'intermediates': {'mean_view': 'mean[None, :, None, None]',
                             'std_view': 'std[None, :, None, None]',
                             'normalized': '(images - mean_view) / std_view'},
           'audit': ['images', 'mean', 'std'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'capstone'},
 'ex105': {'expression': 'masked_scores',
           'intermediates': {'mask_view': 'causal[None, None, :, :]',
                             'masked_scores': 'scores.masked_fill(~mask_view, -1e9)'},
           'audit': ['scores', 'causal'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'capstone'},
 'ex106': {'expression': 'masked',
           'intermediates': {'scale_view': 'head_scale[None, :, None, None]',
                             'mask_view': 'causal[None, None, :, :]',
                             'scaled': 'scores * scale_view',
                             'masked': 'scaled.masked_fill(~mask_view, -1e9)'},
           'audit': ['scores', 'head_scale', 'causal'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'capstone'},
 'ex107': {'expression': 'sq_distance',
           'intermediates': {'x_rows': 'x[:, None, :]',
                             'y_rows': 'y[None, :, :]',
                             'difference': 'x_rows - y_rows',
                             'sq_distance': '(difference ** 2).sum(dim=2)'},
           'audit': ['x', 'y'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'capstone'},
 'ex108': {'expression': 'mixture',
           'intermediates': {'weight_view': 'weights[:, :, None]',
                             'weighted': 'weight_view * experts',
                             'mixture': 'weighted.sum(dim=1)'},
           'audit': ['weights', 'experts'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'capstone'},
 'ex109': {'expression': 'total',
           'intermediates': {'class_weighted': 'losses * class_weights',
                             'mask_view': 'token_mask[:, :, None]',
                             'masked': 'class_weighted * mask_view',
                             'total': 'masked.sum()'},
           'audit': ['losses', 'class_weights', 'token_mask'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'capstone'},
 'ex110': {'expression': 'out',
           'intermediates': {'mean': 'x.mean(dim=2, keepdim=True)',
                             'centered': 'x - mean',
                             'variance': '(centered ** 2).mean(dim=2, keepdim=True)',
                             'normalized': 'centered * (variance + 1e-5).rsqrt()',
                             'affine': 'normalized * gamma + beta',
                             'mask_view': 'token_mask[:, :, None]',
                             'out': 'affine * mask_view'},
           'audit': ['x', 'gamma', 'beta', 'token_mask'],
           'value_exprs': {},
           'backward': [],
           'expected_compatible': True,
           'mode': 'capstone'}}


def _clone(value):
    if isinstance(value, torch.Tensor):
        return value.detach().clone()
    return value


def _aligned_shape(shape, rank):
    return (1,) * (rank - len(shape)) + tuple(shape)


def _incompatible_axes(shapes):
    rank = max((len(shape) for shape in shapes), default=0)
    aligned = [_aligned_shape(shape, rank) for shape in shapes]
    bad = []
    for axis in range(rank):
        non_singletons = {shape[axis] for shape in aligned if shape[axis] != 1}
        if len(non_singletons) > 1:
            bad.append(axis)
    return tuple(bad)


def build_reference(key, supplied):
    """Build hidden shape/value references from the visible fixture tensors."""
    case = CASES[key]
    scope = dict(supplied)
    reference = {}

    for name, value in supplied.items():
        if isinstance(value, torch.Tensor):
            reference[f"{name}_shape"] = tuple(value.shape)

    for name, expression in case["intermediates"].items():
        value = eval(expression, {"torch": torch}, scope)
        scope[name] = value
        reference[name] = _clone(value)
        if isinstance(value, torch.Tensor):
            reference[f"{name}_shape"] = tuple(value.shape)

    audit_names = case["audit"]
    audit_tensors = [scope[name] for name in audit_names]
    audit_shapes = [tuple(tensor.shape) for tensor in audit_tensors]

    output = None
    error = None
    try:
        output = eval(case["expression"], {"torch": torch}, scope)
    except RuntimeError as exc:
        error = exc

    compatible = error is None
    assert compatible is case["expected_compatible"], (key, error)
    reference["compatible"] = compatible

    if not compatible:
        rank = max((len(shape) for shape in audit_shapes), default=0)
        for name, shape in zip(audit_names, audit_shapes, strict=True):
            reference[f"{name}_aligned_shape"] = _aligned_shape(shape, rank)
        reference["incompatible_axes"] = _incompatible_axes(audit_shapes)
        return reference

    assert isinstance(output, torch.Tensor), key
    scope["out"] = output
    reference["out"] = _clone(output)
    reference["out_shape"] = tuple(output.shape)

    if case["mode"] == "aligned":
        rank = output.ndim
        for name, tensor in zip(audit_names, audit_tensors, strict=True):
            aligned = _aligned_shape(tensor.shape, rank)
            reference[f"{name}_aligned_shape"] = aligned
            reference[f"{name}_expanded_axes"] = tuple(
                axis
                for axis, (before, after) in enumerate(zip(aligned, output.shape, strict=True))
                if before == 1 and after != 1
            )

    if case["backward"]:
        dout = supplied["dout"]
        gradients = torch.autograd.grad(
            output,
            [supplied[name] for name in case["backward"]],
            grad_outputs=dout,
        )
        for name, gradient in zip(case["backward"], gradients, strict=True):
            field = f"d{name}"
            reference[field] = gradient.detach().clone()
            reference[f"{field}_shape"] = tuple(gradient.shape)
        reference["y_shape"] = tuple(output.shape)

    for field, expression in case["value_exprs"].items():
        reference[field] = eval(expression, {"torch": torch}, scope)

    return reference
